### ISSUE TITLE
[Feature Request]: Change amount of runes based on which cube recipes you've done

### ISSUE THREAD

**Issue by MojiDuck** [Cerbrus/Diablo2Helper#45]
**Is your feature request related to a problem? Please describe.**
Having to find each rune in the row of runes and manually adjust the number of runes I have after using them for rerolling sockets and/or creating a runeword.

**Describe the solution you'd like**
I'd like to have the option to input what I've done (e.g. I rerolled sockets on an armor 2 times = -2x Tal, -2x Thul -2x Perfect Topaz) and that my list of runes/gems will update to reflect the runes that've been used

**Describe alternatives you've considered**
Manually trying to find where the Thul rune is in the list of runes and lower the amount.

**Comment by Cerbrus** [comment]
Depends on #30
